<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="47634" started-at="2016-11-13T21:37:30Z" finished-at="2016-11-13T21:38:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="47634" started-at="2016-11-13T21:37:30Z" finished-at="2016-11-13T21:38:17Z">
      <class name="com.springer.rd.tests.TestBase">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.springer.rd.tests.TestBase@2c8d66b2]" name="setUp" is-config="true" duration-ms="5619" started-at="2016-11-13T22:37:30Z" finished-at="2016-11-13T22:37:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.springer.rd.tests.TestBase@2c8d66b2]" name="tearDown" is-config="true" duration-ms="162" started-at="2016-11-13T22:38:17Z" finished-at="2016-11-13T22:38:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.springer.rd.tests.TestBase -->
      <class name="com.springer.rd.tests.PositiveSearchTest">
        <test-method status="PASS" signature="positiveAdvancedSearch()[pri:0, instance:com.springer.rd.tests.PositiveSearchTest@d041cf]" name="positiveAdvancedSearch" duration-ms="16124" started-at="2016-11-13T22:37:37Z" finished-at="2016-11-13T22:37:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveAdvancedSearch -->
        <test-method status="FAIL" signature="positiveAdvancedSearchBug()[pri:0, instance:com.springer.rd.tests.PositiveSearchTest@d041cf]" name="positiveAdvancedSearchBug" duration-ms="15704" started-at="2016-11-13T22:37:53Z" finished-at="2016-11-13T22:38:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at com.springer.rd.pages.MainSearchPage.checkResults(MainSearchPage.java:148)
	at com.springer.rd.tests.PositiveSearchTest.positiveAdvancedSearchBug(PositiveSearchTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveAdvancedSearchBug -->
        <test-method status="PASS" signature="positiveSimpleSearch()[pri:0, instance:com.springer.rd.tests.PositiveSearchTest@d041cf]" name="positiveSimpleSearch" duration-ms="8482" started-at="2016-11-13T22:38:09Z" finished-at="2016-11-13T22:38:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveSimpleSearch -->
      </class> <!-- com.springer.rd.tests.PositiveSearchTest -->
      <class name="com.springer.rd.tests.NegativeSearchTest">
        <test-method status="PASS" signature="negativeSimpleSearch()[pri:0, instance:com.springer.rd.tests.NegativeSearchTest@129a8472]" name="negativeSimpleSearch" duration-ms="1524" started-at="2016-11-13T22:37:35Z" finished-at="2016-11-13T22:37:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeSimpleSearch -->
      </class> <!-- com.springer.rd.tests.NegativeSearchTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
